document.head.insertAdjacentHTML('beforeend',`<style>
.demo-ribbon{position:fixed;z-index:20;top:0;left:240px;right:0;height:28px;display:grid;place-items:center;background:#f5dfd7;color:#854533;font-size:12px;font-weight:650;letter-spacing:.03em}.sidebar{padding-top:42px}main{padding-top:62px}
@media(max-width:760px){body{min-width:0!important}.demo-ribbon{left:0}.app-shell{display:block}.sidebar{position:static;width:auto;height:auto;padding:45px 14px 12px}.sidebar .brand{padding-bottom:12px}.sidebar nav{display:flex;overflow-x:auto}.nav-link{white-space:nowrap}.privacy-note{display:none}main{padding:24px 16px 60px}.hero{grid-template-columns:1fr}.weather-panel{min-height:220px}.dashboard-row,.profile-grid,.outfit-results{grid-template-columns:1fr}.toolbar{flex-wrap:wrap}.toolbar .search{flex-basis:100%}.items-strip{grid-template-columns:repeat(2,1fr)}.page-head h1,.hero-copy h1{font-size:2rem}.hero-copy{padding:28px 24px}.outfit-controls{align-items:stretch;flex-direction:column}.dialog-body{grid-template-columns:1fr}.dialog-visual{height:280px}}
</style>`);
const items=[
['Боди шоколадного цвета','Верха','коричневый','body.jpg'],['Брюки чёрные','Низы','чёрный','black-pants.jpg'],['Джинсовая куртка','Вторые слои','синий','denim-jacket.jpg'],['Джинсы светлые','Низы','синий','light-jeans.jpg'],['Кеды золотистые','Обувь','золотой','gold-sneakers.jpg'],['Кожаные кеды','Обувь','белый','leather-sneakers.jpg'],['Куртка серая','Верхняя одежда','серый','gray-jacket.jpg'],['Платье чёрное','Платья и комбинезоны','чёрный','dress.jpg'],['Ремень кожаный','Ремни','коричневый','belt.jpg'],['Рубашка белая','Верха','белый','white-shirt.jpg'],['Свитер коричневый','Вторые слои','коричневый','brown-sweater.jpg'],['Сумка коричневая','Сумки','коричневый','brown-bag.jpg'],['Сумка кросс-боди','Сумки','чёрный','crossbody-bag.jpg'],['Топ белый','Верха','белый','white-top.jpg'],['Футболка бежевая','Верха','бежевый','beige-tshirt.jpg'],['Кроссовки бежевые','Обувь','бежевый','beige-trainers.jpg']
].map((x,i)=>({id:i+1,name:x[0],category:x[1],color:x[2],image:'assets/'+x[3],season:['Всесезон','Демисезон','Лето'][i%3],style:i%4===0?'Деловой':'Повседневный'}));
const cats=[...new Set(items.map(x=>x.category))],navItems=[['home','⌂','Главная'],['wardrobe','▦','Гардероб'],['add','＋','Добавить вещи'],['outfits','◈','Подобрать образ'],['favorites','♥','Избранные образы'],['profile','○','Профиль'],['settings','⚙','Настройки']];
const state={route:'home',search:'',cat:'',favorite:false,liked:0};const app=document.querySelector('#app'),nav=document.querySelector('#nav'),dialog=document.querySelector('#itemDialog');
const e=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function toast(t){const x=document.querySelector('#toast');x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2200)}
function head(k,t,s='',a=''){return `<header class="page-head"><div><p class="eyebrow">${k}</p><h1>${t}</h1>${s?`<p>${s}</p>`:''}</div>${a}</header>`}
function card(x){return `<article class="item-card" data-item="${x.id}" tabindex="0"><div class="item-image"><img src="${x.image}" alt="${e(x.name)}"></div><div class="item-info"><b>${e(x.name)}</b><span>${x.category} · ${x.color}</span></div></article>`}
function bind(){document.querySelectorAll('[data-route]').forEach(x=>x.onclick=()=>location.hash=x.dataset.route);document.querySelectorAll('[data-item]').forEach(x=>x.onclick=()=>openItem(+x.dataset.item))}
function home(){const stats=cats.slice(0,4).map(c=>[c,items.filter(x=>x.category===c).length]);app.innerHTML=`<section class="hero"><div class="hero-copy"><p class="eyebrow">Сегодня в гардеробе</p><h1>Соберите образ<br>для своего дня</h1><p>Персональный каталог помогает увидеть все вещи вместе и составить комплект с учётом погоды и повода.</p><div class="hero-actions"><button class="btn primary" data-route="outfits">Посмотреть образы</button><button class="btn ghost" data-route="wardrobe" style="color:white;border-color:#566263">Открыть каталог</button></div></div><div class="weather-panel"><div class="weather-top"><div><small>Москва · демонстрация</small><div class="weather-temp">12°</div><b>Переменная облачность</b></div><span style="font-size:2rem">☼</span></div><div class="weather-meta"><div><b>10°</b><span>ощущается</span></div><div><b>7 км/ч</b><span>ветер</span></div><div><b>0 мм</b><span>осадки</span></div></div></div></section><div class="dashboard-row"><section class="card section-card"><div class="section-title"><h2>Недавно добавленные</h2><button class="text-link" data-route="wardrobe">Весь гардероб</button></div><div class="items-strip">${items.slice(0,4).map(x=>`<div class="mini-item" data-item="${x.id}"><div class="mini-img"><img src="${x.image}"></div><b>${x.name}</b><span>${x.category}</span></div>`).join('')}</div></section><section class="card section-card"><div class="section-title"><h2>В демо-каталоге</h2><span class="badge">${items.length} вещей</span></div><div class="stats">${stats.map(x=>`<div class="stat"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('')}</div></section></div>`;bind()}
function wardrobe(){const shown=items.filter(x=>(!state.search||x.name.toLowerCase().includes(state.search.toLowerCase()))&&(!state.cat||x.category===state.cat));app.innerHTML=head('Каталог','Мой гардероб',`${shown.length} из ${items.length} вещей`,`<button class="btn accent" data-route="add">＋ Добавить вещи</button>`)+`<div class="toolbar"><div class="search"><span>⌕</span><input id="search" class="field" value="${e(state.search)}" placeholder="Поиск по названию"></div><select id="cat" class="select"><option value="">Все категории</option>${cats.map(c=>`<option ${c===state.cat?'selected':''}>${c}</option>`).join('')}</select><select class="select"><option>Все цвета</option><option>Белый</option><option>Чёрный</option></select><select class="select"><option>Все сезоны</option><option>Лето</option><option>Демисезон</option></select></div><div class="wardrobe-grid">${shown.map(card).join('')}</div>`;bind();document.querySelector('#search').oninput=x=>{state.search=x.target.value;wardrobe()};document.querySelector('#cat').onchange=x=>{state.cat=x.target.value;wardrobe()}}
function add(){app.innerHTML=head('Пополнение','Добавить вещи','В полной версии фотографии обрабатываются и сохраняются локально')+`<div class="upload-zone" id="up"><div class="upload-icon">＋</div><h2>Перетащите фотографии сюда</h2><p>В демоверсии показан интерфейс сценария загрузки</p><button class="btn accent" style="margin-top:18px">Выбрать фотографии</button></div><div class="upload-help"><div class="card help-card"><b>1 · Подготовка</b><span>Удаление светлого фона и обрезка.</span></div><div class="card help-card"><b>2 · Распознавание</b><span>Предложение категории, цвета и сезона.</span></div><div class="card help-card"><b>3 · Проверка</b><span>Все характеристики можно исправить.</span></div></div>`;document.querySelector('#up').onclick=()=>toast('Демо: в полной версии откроется выбор файлов')}
const looks=[[10,2,3,7,6,12],[15,4,11,7,16,13,9]];function look(ids,n){return `<article class="card outfit-card"><div class="outfit-card-head"><h3>Образ ${n}</h3><span class="badge">Работа</span></div><div class="collage">${ids.map(id=>{const x=items[id-1];return `<div class="collage-item" data-item="${id}"><img src="${x.image}"><span>${x.name}</span></div>`}).join('')}</div><div class="outfit-actions"><button class="btn like">${state.liked===n?'♥ Нравится':'♡ Нравится'}</button><button class="btn dislike">Не нравится</button><button class="btn fav">${state.favorite?'★ В избранном':'☆ В избранное'}</button></div></article>`}
function outfits(){app.innerHTML=head('Рекомендации','Подобрать образ','Два варианта с учётом повода и погоды')+`<section class="card outfit-controls"><div class="control"><label>Повод</label><select class="select"><option>Прогулка</option><option selected>Работа</option><option>Мероприятие</option><option>Торжественный выход</option></select></div><div class="control" style="flex:1"><label>Обязательная вещь</label><select class="select"><option>Не закреплять</option>${items.map(x=>`<option>${x.name}</option>`).join('')}</select></div><button id="refresh" class="btn accent">Подобрать 2 образа</button></section><div class="outfit-results">${looks.map((x,i)=>look(x,i+1)).join('')}</div>`;bindLooks()}
function bindLooks(){bind();document.querySelectorAll('.like').forEach((b,i)=>b.onclick=()=>{state.liked=i+1;toast('Оценка учтена');outfits()});document.querySelectorAll('.dislike').forEach(b=>b.onclick=()=>toast('Оценка учтена'));document.querySelectorAll('.fav').forEach(b=>b.onclick=()=>{state.favorite=!state.favorite;toast(state.favorite?'Добавлено в избранное':'Удалено из избранного');outfits()});document.querySelector('#refresh')?.addEventListener('click',()=>toast('Подобраны два варианта'))}
function favorites(){app.innerHTML=head('Сохранённое','Избранные образы',state.favorite?'1 образ':'Пока нет сохранённых образов')+`<div class="outfit-results">${state.favorite?look(looks[0],1):'<div class="empty card" style="grid-column:1/-1">Добавьте образ в избранное на экране подбора.</div>'}</div>`;if(state.favorite)bindLooks()}
function profile(){app.innerHTML=head('Личные параметры','Профиль','Демонстрация данных для алгоритма')+`<div class="profile-grid"><section class="card form-card"><h2>Основные данные</h2><div class="form-grid">${[['Рост, см','168'],['Вес, кг','58'],['Грудь, см','88'],['Талия, см','68'],['Бёдра, см','94'],['Плечи, см','39']].map(x=>`<div class="form-field"><label>${x[0]}</label><input class="field" value="${x[1]}"></div>`).join('')}<div class="form-field full"><label>Город</label><input class="field" value="Москва"></div></div></section><section class="card form-card"><h2>Приватность</h2><div class="privacy-card card"><h3>Только локальный анализ</h3><p>Фотографии фигуры не отправляются во внешние сервисы. Сохраняются только числовые признаки.</p></div><button class="btn accent" style="margin-top:18px" onclick="toast('Демо: профиль сохранён')">Сохранить профиль</button></section></div>`}
function settings(){app.innerHTML=head('Управление','Настройки','Пример локальных настроек')+`<div class="settings-list"><section class="card setting"><div><h3>Резервная копия</h3><p>Экспорт базы и изображений в один локальный файл.</p></div><button class="btn primary" onclick="toast('Демо: копия создана')">Создать копию</button></section><section class="card setting"><div><h3>Место хранения</h3><p>Полная версия хранит данные только на компьютере.</p></div><span class="badge">Локально</span></section></div>`}
function openItem(id){const x=items[id-1];dialog.innerHTML=`<button class="dialog-close">×</button><div class="dialog-body"><div class="dialog-visual"><img src="${x.image}"></div><div class="dialog-content"><p class="eyebrow">${x.category}</p><h2>${x.name}</h2><div class="form-grid">${[['Цвет',x.color],['Сезон',x.season],['Стиль',x.style],['Материал','Хлопок / смесовая ткань']].map(y=>`<div class="form-field"><label>${y[0]}</label><input class="field" readonly value="${y[1]}"></div>`).join('')}</div><div class="dialog-actions"><span class="badge">Карточка вещи</span><button class="btn primary" id="build">Собрать образ с этой вещью</button></div></div></div>`;dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.querySelector('#build').onclick=()=>{dialog.close();location.hash='outfits';setTimeout(()=>toast(`${x.name} закреплена`),150)};dialog.showModal()}
function render(){state.route=location.hash.slice(1)||'home';nav.innerHTML=navItems.map(x=>`<button class="nav-link ${x[0]===state.route?'active':''}" data-route="${x[0]}"><span class="ico">${x[1]}</span>${x[2]}</button>`).join('');({home,wardrobe,add,outfits,favorites,profile,settings}[state.route]||home)();bind()}
window.addEventListener('hashchange',render);render();

